# Generated by Django 4.1.5 on 2023-04-01 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aigerim',
            name='image',
            field=models.ImageField(blank=True, default='', upload_to='kartinki/images', verbose_name='фотография'),
        ),
    ]
